package com.acme.mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2018-12-11T23:22:15.342+03:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://thomas-bayer.com/blz/", name = "BLZServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface BLZServicePortType {

    @WebMethod
    @Action(output = "//thomas-bayer.com/blz/BLZService/getBankResponse")
    @RequestWrapper(localName = "getBank", targetNamespace = "http://thomas-bayer.com/blz/", className = "com.acme.mypackage.GetBankType")
    @ResponseWrapper(localName = "getBankResponse", targetNamespace = "http://thomas-bayer.com/blz/", className = "com.acme.mypackage.GetBankResponseType")
    @WebResult(name = "details", targetNamespace = "http://thomas-bayer.com/blz/")
    public com.acme.mypackage.DetailsType getBank(
        @WebParam(name = "blz", targetNamespace = "http://thomas-bayer.com/blz/")
        java.lang.String blz
    );
}
